### ISSUE TITLE
Name scrubbing issues

### ISSUE THREAD

**Issue by srinivasgumdelli** [datascopeanalytics/scrubadub#19]
I was testing out this impressive library and my text files had some names which start with a lower case letter (example: sarah), these kinds were not being filtered. 

One more issue that I found with 1.0.3 version was 
```
Hello. Please testing
```
will be replaced by
```
{{NAME}}. {{NAME}} testing
```

Thanks,
Sri

**Comment by deanmalmgren** [comment]
Thanks for bringing this to our attention, @srinivasgumdelli! After digging around a bit, it appears that the problem with words like `Hello` and `Please` started with textblob version 0.10.1. I've [pinned the textblob version to 0.10.0](https://github.com/datascopeanalytics/scrubadub/blob/master/requirements/python#L1) which should address the Hello and Please issue you were having.

Lower case names remains an issue though, which I suspect will be better addressed by using machine learning techniques (#16) vs strict natural language processing. I added [a unit test](https://github.com/datascopeanalytics/scrubadub/blob/master/tests/test_names.py#L24-L30) for this so we can be sure to address that in a more robust way in the future. For now, we're skipping the unit test.

If you have any other suggestions for the package, please let me know!

**Comment by deanmalmgren** [comment]
Oh, and I just released version 1.1.0 of scrubadub that should address this issue. You should be able to `pip install -U scrubadub` and hopefully that will address most of the problems you were having.
