### ISSUE TITLE
Misses social security number

### ISSUE THREAD

**Issue by gabegaster** [datascopeanalytics/scrubadub#23]
Hey Datascope, Cool project!

I tried out the demo and saw that it missed a "social security number":

![screen shot 2016-06-14 at 12 05 17 am](https://cloud.githubusercontent.com/assets/1449337/16030908/f457d20e-31c3-11e6-8bc9-f3fb4a1786fa.png)

UPDATE: Hmm. I just tried to reproduce the error in a console and could not. ¯\_(ツ)_/¯  But the behavior on the website persists.

**Comment by gabegaster** [comment]
In the process of testing, I saw and added a missing requirement (yaml). Also, I suspect there might be a missing colors file, so I added behavior to tests/run.py that has it run in color-less mode if there aren't colors.

**Comment by deanmalmgren** [comment]
Thanks for the note, @gabegaster!! scrubadub.io was not using the latest version of `scrubadub`. My bad, dawg.

I just updated it to the latest version so it should work as advertised. CC @adamajm
